server:
  port: 3003
  template: config.template


      # user: clashsub时传递的url参数,区分不同的订阅者
      # tag: frontend中使用的tag，用作traffic monitor
      # 格式为 type:port:remark
      # clashsub中也使用tag，作为返回的proxy的user
      # sub: clashsub订阅时只返回为true的元素
inbounds:
  shadowsocks:
    - user: nicof
      tag: "ss:4000:nicof"
      server: 10.1.2.245
      cipher: aes-256-cfb
      password: 90Ad!23
      udp: true
      sub: true

    - user: nicof
      tag: "ss:4100:nicof"
      server: 10.1.2.245
      cipher: aes-256-cfb
      password: 90A!23
      udp: true
      sub: true

    - user: nico
      tag: "ss:4001:nico"
      server: 10.1.2.245
      cipher: aes-256-cfb
      password: 301b
      udp: true
      sub: true

    - user: nico
      tag: "ss:4101:nico"
      server: 10.1.2.245
      cipher: aes-256-cfb
      password: 30s1b
      udp: true
      sub: true

    - user: chuan
      tag: "ss:4002:chuan"
      server: 10.1.2.245
      cipher: aes-256-cfb
      password: 3e1b
      udp: true
      sub: true

    - user: chuan
      tag: "ss:4102:chuan"
      server: 10.1.2.245
      cipher: aes-256-cfb
      password: o0s1b
      udp: true
      sub: true
  
    - user: eagle
      tag: "ss:4003:eagle"
      server: 10.1.2.245
      cipher: aes-256-cfb
      password: 3e1b
      udp: true
      sub: true

    - user: eagle
      tag: "ss:4103:eagle"
      server: 10.1.2.245
      cipher: aes-256-cfb
      password: o0s1b
      udp: true
      sub: true

    - user: wei
      tag: "ss:4004:wei"
      server: 10.1.2.245
      cipher: aes-256-cfb
      password: 3e1b
      udp: true
      sub: true

    - user: wei
      tag: "ss:4104:wei"
      server: 10.1.2.245
      cipher: aes-256-cfb
      password: o0s1b
      udp: true
      sub: true

  vmess:
    - user: eagle
      tag: "vmess:4010:eagle"
      server: 10.1.2.245
      cipher: auto
      uuid: e2791dbb-f350-4a71-998a-da3b184a1cef
      alterId: 64
      network: ws
      sub: true

  socks5:
    - user: eagle
      tag: "socks5:4020:noauth"
      server: 10.1.2.245
      udp: true
      auth: noauth
      sub: true
    - user: eagle
      tag: "socks5:4021:auth"
      server: 10.1.2.245
      udp: true
      auth: password
      username: usersocks5
      password: usernopasssocks5
      sub: true

  http:
    - user: eagle
      tag: "http:4030:noauth"
      server: 10.1.2.245
      sub: true
    - user: eagle
      tag: "http:4031:auth"
      server: 10.1.2.245
      username: user2
      password: usernopass2
      sub: true

mysql:
  enable: false
  dsn: <user>[:password]@tcp(localhost)/
  maxIdleConns: 0
  maxOpenConns: 50
mongodb:
  enable: false
  url: mongodb://localhost:27017

log:
  level: debug
  logfile: ''
  showFullTime: true
  reportCaller: false

cors:
  allowOrigins: ['*']
  allowMethods: [ 'GET', 'POST']
  allowHeaders: ['Origin', 'Content-Length', 'Content-Type']
  maxAge: 43200